### ISSUE TITLE
I hope they help me with this and give me a solution

### ISSUE THREAD

**Issue by DANI002428** [Allen98637/Funkin-master---share#1]
well, today I tried to compile the mod to a version that is playable for 32 Bits, but I got an error and I would like to know how it is possible to fix it.

`cl.exe -nologo /WX- /fp:precise -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdC:\Users\Downloads\GalaxyMod-main\export\release\windows\obj\obj/msvc19-ncxp/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -arch:SSE2 -IC:/HaxeToolkit/haxe/lib/hxcpp/4,2,1/include -DHXCPP_VISIT_ALLOCS(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe]   
 - src/resources/__res_10.cpp  [optim-none]
Error: __res_10.cpp
./src/resources/__res_10.cpp(2173756): fatal error C1060: insufficient heap space in compiler`

Maybe this way the last line of error will not be written, but it is that I translated it so that you understand, because it is originally in Spanish.

**Comment by Allen98637** [comment]
Since it said "insufficient heap space", I guess it's either your storage is not enough or you RAM size is not enough.
Sorry for the late reply but I don't see here often.
Also I know few about 32 bit and Mac, I was trying to build the mac version but it failed, hope I can help you as far as I can
